// AUTH_ACTIONS
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

// USER_ACTIONS
export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';

// CHAT_ACTIONS
export const GET_CHAT = 'GET_CHAT';
export const GET_CHATS = 'GET_CHATS';
export const CREATE_CHAT = 'CREATE_CHAT';
export const UPDATE_CHAT = 'UPDATE_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DELIVER_MESSAGE_TO_ONLINE_CLIENTS = 'DELIVER_MESSAGE_TO_ONLINE_CLIENTS';
export const DELIVER_CREATED_CHAT_TO_ONLINE_CLIENTS = 'DELIVER_CREATED_CHAT_TO_ONLINE_CLIENTS';
export const DELIVER_ONLINE_USERS_TO_ONLINE_CLIENTS = 'DELIVER_ONLINE_USERS_TO_ONLINE_CLIENTS';

// ERROR_ACTIONS
export const RESET_ERRORS = 'RESET_ERRORS';
