export const JOIN_CHAT = 'JOIN_CHAT';
export const SET_ONLINE_USER = 'SET_ONLINE_USER';
export const SET_OFFLINE_USER = 'SET_OFFLINE_USER';
export const REGISTER_SOCKET_USER_ID = 'REGISTER_SOCKET_USER_ID';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const CREATED_CHAT = 'CREATED_CHAT';