module.exports = {
  REGISTER_SOCKET_USER_ID: 'REGISTER_SOCKET_USER_ID',
  JOIN_CHAT: 'JOIN_CHAT',
  REGISTER_SOCKET_USER_ID: 'REGISTER_SOCKET_USER_ID',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVED_MESSAGE: 'RECEIVED_MESSAGE',
  CREATED_CHAT: 'CREATED_CHAT',
  CREATE_CHAT: 'CREATE_CHAT'
}