module.exports = {
  JOIN_CHAT: 'JOIN_CHAT',
  SET_ONLINE_USER: 'SET_ONLINE_USER',
  SET_OFFLINE_USER: 'SET_OFFLINE_USER',
  RECEIVED_ONLINE_USERS: 'RECEIVED_ONLINE_USERS',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVED_MESSAGE: 'RECEIVED_MESSAGE',
  CREATED_CHAT: 'CREATED_CHAT',
  CREATE_CHAT: 'CREATE_CHAT',
};
